### ISSUE TITLE
Errors when running thingy52.py

### ISSUE THREAD

**Issue by frazzyfin** [wlgrd/thingy52_homeassistant#1]
I've followed your instructions to get this working and put the thingy52.py file in the right directory, but am getting errors when homeassistant starts:

2018-03-02 19:24:02 ERROR (MainThread) [homeassistant.components] Testing configuration at /home/homeassistant/.homeassistant
ERROR:homeassistant.loader:Error loading custom_components.sensor.thingy52. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sensor/thingy52.py", line 15, in <module>
    from bluepy import btle, thingy52
ImportError: No module named 'bluepy'
ERROR:homeassistant.loader:Unable to find component sensor.thingy52
Failed config
  General Errors: 
    - Platform not found: sensor.thingy52

Successful config (partial)

Looks like it's something to do with bluepy which I have confirmed is working in python3 but not for python2. How can I get homeassistant to run the script using python3?

**Comment by wlgrd** [comment]
It seems like it is running with python 3.5 in your setup. Are you sure bluepy is working there?
Try just starting python (and confirm it is 3.5 that is starting), and do an `import bluepy`. If that fails, I don't know what is wrong with your setup. Also, I haven't looked at this since HA 0.57, so maybe there has been some changes I'm not up to date with. 
Also, try removing all instances of bluepy and do a `python3.5 -m pip install bluepy` to make sure it is installed with the right version.
Let me know how it goes :)

**Comment by wlgrd** [comment]
Look at the last comment in #2 . Same problem. I just recreated the environment from scratch on a new raspberry pi. You can also have a look at the wiki, which I am currently trying to update a little bit for my own experimentations https://github.com/chriswils/thingy52_homeassistant/wiki/Installing-HomeAssistant
