### ISSUE TITLE
Python 3.7 errors

### ISSUE THREAD

**Issue by moscaen** [wlgrd/thingy52_homeassistant#8]
Hi,

I followed your instruction to install the sensor, but I get the following error:

`2020-08-08 13:28:41 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up thingy52 platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/thingy52/sensor.py", line 157, in setup_platform
    thingy.environment.enable()
  File "/srv/homeassistant/lib/python3.7/site-packages/bluepy/thingy52.py", line 147, in enable
    self.environment_service = self.periph.getServiceByUUID(self.serviceUUID)
  File "/srv/homeassistant/lib/python3.7/site-packages/bluepy/btle.py", line 490, in getServiceByUUID
    raise BTLEGattError("Service %s not found" % (uuid.getCommonName()), rsp)
bluepy.btle.BTLEGattError: Service ef680200-9b35-4933-9b10-52ffa9740042 not found
`
These are the steps to reproduce the issue:
I have cloned the folder in my .configuration folder so that the thingy52.py is at /home/homeassistant/.homeassistant/custom_components/thingy52

In /home/homeassistant/.homeassistant I have copied your configuration.yaml and edited to include the mac addresses of my 2 thingy. I have also commented out some stuff I don't need (i.e. introduction, frontend
, conversation, map, platform: yr, tts: - platform google)

Then I run hass --script check_config and I get as output 
Testing configuration at /home/homeassistant/.homeassistant

Then I run hass and I get the aforementioned error message.

Could you help me out?
Thanks and keep up the good work!

**Comment by moscaen** [comment]
Ah no, nevermind: turning them on and off fixed my issue.
